### ISSUE TITLE
remote-desktop module should provision remote chromoting tools

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/hpc-toolkit#1019]
### Describe the bug

After deploying https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/main/community/modules/remote-desktop/chrome-remote-desktop and ssh'ing into the vm instance and running the chromoting setup command snippet according to the provided instructions, the chromoting tools don't seem to be installed on the system.

### Steps to reproduce

https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/community/modules/remote-desktop/chrome-remote-desktop/README.md#setting-up-the-remote-desktop

### Expected behavior

Setup process continue and ask the user to enter a pin.

### Actual behavior

The chromoting setup command snippet fails with the following command:
```
-bash: /opt/google/chrome-remote-desktop/start-host: No such file or directory
```

### Version (`ghpc --version`)

```
hpc-toolkit 👺 ./ghpc --version
ghpc version - not built from official release
Built from 'develop' branch.
Commit info: v1.14.0-84-g907d0e7d
```

### Blueprint

```yaml
blueprint_name: remote-desktop

vars:
  project_id: catx-demo-radlab
  deployment_name: radlab-remote-desktop
  region: us-central1
  zone: us-central1-c

deployment_groups:
- group: primary
  modules:
  - id: network1
    source: modules/network/vpc

  - id: remote-desktop
    source: community/modules/remote-desktop/chrome-remote-desktop
    use: [network1]
    settings:
      install_nvidia_driver: true

```

### Expanded Blueprint

If applicable, please attach or paste the expanded blueprint. The expanded blueprint can be obtained by running `ghpc expand your-blueprint.yaml`.

Disregard if the bug occurs when running `ghpc expand ...` as well.

```yaml
blueprint_name: remote-desktop
validators:
  - validator: test_module_not_used
    inputs: {}
  - validator: test_project_exists
    inputs:
      project_id: ((var.project_id))
  - validator: test_apis_enabled
    inputs: {}
  - validator: test_region_exists
    inputs:
      project_id: ((var.project_id))
      region: ((var.region))
  - validator: test_zone_exists
    inputs:
      project_id: ((var.project_id))
      zone: ((var.zone))
  - validator: test_zone_in_region
    inputs:
      project_id: ((var.project_id))
      region: ((var.region))
      zone: ((var.zone))
validation_level: 1
vars:
  deployment_name: radlab-remote-desktop
  labels:
    ghpc_blueprint: remote-desktop
    ghpc_deployment: radlab-remote-desktop
  project_id: catx-demo-radlab
  region: us-central1
  zone: us-central1-c
deployment_groups:
  - group: primary
    terraform_backend:
      type: ""
      configuration: {}
    modules:
      - source: modules/network/vpc
        kind: terraform
        id: network1
        modulename: ""
        use: []
        wrapsettingswith: {}
        settings:
          deployment_name: ((var.deployment_name))
          project_id: ((var.project_id))
          region: ((var.region))
        required_apis:
          ((var.project_id)):
            - compute.googleapis.com
      - source: community/modules/remote-desktop/chrome-remote-desktop
        kind: terraform
        id: remote-desktop
        modulename: ""
        use:
          - network1
        wrapsettingswith: {}
        settings:
          deployment_name: ((var.deployment_name))
          install_nvidia_driver: true
          labels:
            ghpc_role: remote-desktop
          network_self_link: ((module.network1.network_self_link))
          project_id: ((var.project_id))
          region: ((var.region))
          subnetwork_self_link: ((module.network1.subnetwork_self_link))
          zone: ((var.zone))
        required_apis:
          ((var.project_id)): []
    kind: terraform
terraform_backend_defaults:
  type: ""
  configuration: {}
```

### Execution environment

- OS: `Linux proppy0 5.19.11-1rodete1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1rodete1 (2022-10-31) x86_64 GNU/Linux`
- Shell (To find this, run `ps -p $$`): `  82709 pts/2    00:00:00 bash`
- go version: `go version go1.20.1 linux/amd64`

### Additional context

This can be easily worked around by installing https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb after ssh'ing in the vm and before running the chromoting setup command snippet.
