### ISSUE TITLE
Private static IP address won't set on the Slurm controller node.

### ISSUE THREAD

**Issue by ek-nag** [GoogleCloudPlatform/hpc-toolkit#1229]
Hello,

I am building a Slurm cluster and experiencing an issue when trying to set a static private IP address for my controller node. I have a static private IP address reserved in my VPC Subnet (`172.17.140.40`). In my HPC Toolkit blueprint, I am assigning this reserved IP address by defining `network_ip` setting like in the example below.

```bash
  - source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    kind: terraform
    id: slurm_controller
    settings:
      machine_type: e2-standard-8
      instance_image:
        family: $(vars.controller_image)
        project: $(vars.project_id)
      enable_oslogin: False
      disk_type: pd-standard
      disk_size_gb: 50
      subnetwork_self_link: $(vars.subnet_name)
      network_ip: 172.17.140.40
      tags: ["iap"]
      service_account:
        email: $(vars.sa_id)
        scopes:
        - https://www.googleapis.com/auth/cloud-platform
        - https://www.googleapis.com/auth/monitoring.write
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/devstorage.read_write
    use:
    - hpc_network
    - partition_0
    - homefs
```

If I look at the generated Terraform code, I can see IP address reflecting in the main.tf

```bash
module "slurm_controller" {
  source                    = "./modules/embedded/community/modules/scheduler/schedmd-slurm-gcp-v5-controller"
  deployment_name           = var.deployment_name
  disk_size_gb              = 50
  disk_type                 = "pd-standard"
  enable_oslogin            = false
  instance_image = {
    family  = var.controller_image
    project = var.project_id
  }
  labels            = merge(var.labels, { ghpc_role = "scheduler", })
  machine_type      = "e2-standard-8"
  network_ip        = "172.17.140.40"
  network_self_link = module.hpc_network.network_self_link
  network_storage   = flatten([module.homefs.network_storage, module.optfs.network_storage])
  partition         = flatten([module.partition_0.partition, module.partition_1.partition, module.partition_2.partition])
  project_id        = var.project_id
  region            = var.region
  service_account = {
    email  = var.sa_id
    scopes = ["https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/monitoring.write", "https://www.googleapis.com/auth/logging.write", "https://www.googleapis.com/auth/devstorage.read_
write"]
  }
  subnetwork_self_link = var.subnet_name
  tags                 = ["iap"]
  zone                 = var.zone
}
```

Unfortunately, after node boots, it does not get the static IP address assigned to it. Instead, it gets automatically generated IP. 
I think the problem is that https://github.com/SchedMD/slurm-gcp/tree/5.6.2/terraform/slurm_cluster/modules/slurm_controller_instance assigns a static IP address to the node template here https://github.com/SchedMD/slurm-gcp/blob/5.6.2/terraform/slurm_cluster/modules/slurm_instance_template/main.tf#L90 instead of the node itself.

Forgive me if I am using the module incorrectly and if this is expected behaviour, if not - is this a bug in the module? It kind of makes impossible to set static IP address for the controller node. Would you be able to have a look at this?

In the `gcloud compute instances create` I would use argument such as  `--network-interface=network-tier=PREMIUM,private-network-ip=172.17.140.40,stack-type=IPV4_ONLY,subnet=subnet`

Thank you!

**Comment by cboneti** [comment]
Hi, 

This sounds like a real bug. We have reached out to SchedMD about this and will come back to you shortly.

**Comment by cboneti** [comment]
Quick update here, we expect SchedMD to release a fix for this some time next week.

**Comment by bsngardner** [comment]
I took another look at this, and there appears to be a problem with `network_ip` and `static_ips` being both defined in the wrapper module. We are looking at fixing this, but `static_ips` should work since it _is_ passed to the `slurm_controller_instance` module. It is a list, the first is used.

Something like this should work, copied and modified from yours above:
```
- source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    kind: terraform
    id: slurm_controller
    settings:
      machine_type: e2-standard-8
      instance_image:
        family: $(vars.controller_image)
        project: $(vars.project_id)
      enable_oslogin: False
      disk_type: pd-standard
      disk_size_gb: 50
      subnetwork_self_link: $(vars.subnet_name)
      static_ips:
      - 172.17.140.40
      tags: ["iap"]
      service_account:
        email: $(vars.sa_id)
        scopes:
        - https://www.googleapis.com/auth/cloud-platform
        - https://www.googleapis.com/auth/monitoring.write
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/devstorage.read_write
    use:
    - hpc_network
    - partition_0
    - homefs
```
