### ISSUE TITLE
C2D Compact Placement Policy not working

### ISSUE THREAD

**Issue by m4r1k** [GoogleCloudPlatform/hpc-toolkit#158]
Slurm won't allow to deploy a compute partition using the Compact Placement Policy together with C2D instance type.

Follows the Slurm error
```
2022-03-21 10:47:25,970 2945 47377888545088 resume.py ERROR: Unsupported placement policy configuration. Please utilize c2 machine type.
```

Follows the HPC-Toolkit Compute Partition definition
```
  # Slurm Compute partition
  - source: resources/third-party/compute/SchedMD-slurm-on-gcp-partition
    kind: terraform
    id: compute_partition
    use:
    - network1
    - homefs
    settings:
      partition_name: compute
      max_node_count: 4
      enable_placement: true
      machine_type: "c2d-highcpu-112"
      compute_disk_type: "pd-balanced"
      image_hyperthreads: false
```

This happens due to an hardcoded condition in Slurm that allows the Compact Placement Policy to work only with C2 instances.
https://github.com/SchedMD/slurm-gcp/blob/master/scripts/resume.py#L357-L363
