### ISSUE TITLE
How to use image-builder.yaml to install a docker image to template VM

### ISSUE THREAD

**Issue by noahharrison64** [GoogleCloudPlatform/hpc-toolkit#1598]
Hi,

I'm using the [image-builder blue print ](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/examples/README.md#image-builderyaml-)to create an auto-scaling HPC that loads each compute node as a VM based on a template image. I have got it working so the template image has docker installed, which I achieved by modifying the contents of the startup script module. However, it would be very useful if I could also pull a private docker repo/image to the template image, since then I won't have to run docker pull each time a compute node is booted up, as this is very time consuming (26GB image). 

I envisage there are two ways of achieving this, however I haven't fully worked out the plan for either.

1) Update the contents of the start up script so that it pulls the docker image, however this would require authenticating the temporary VM, which I understand to be an interactive process (requiring an authentication code or key, and I don't know how i would supply this to the process).

2) Create a VM template based on the template generated by packer, and in that VM pull the docker image. Save this new VM as a template and specify it in the blueprint rather than specifying the packer generated VM template. The issue I have encountered here is being unable to actually create a VM based on a packer template, each time I try it never appears. I am wondering if this is because the template VM is meant to auto-close / delete itself? 

Any advice on either of these options would be greatly appreciated.

Thanks,
Noah

**Comment by rohitramu** [comment]
Hi Noah,

I have a couple of questions about the issue you're facing:
- Could you please share the blueprint which includes all your changes (e.g. with the docker installation script)?
- Where is the docker image hosted?  E.g. is it in a private DockerHub registry, Artifact Registry, etc.?
- What are you using for a scheduler?  Are you using Slurm?

Kind regards,
Rohit

**Comment by tpdownes** [comment]
@noahharrison64 the reason we are asking the questions above, especially location of Docker image, is that if you are using Google Cloud Artifiact Registry, we can guide you toward a solution that would have the authentication necessary to pull it while building the image. In any case, having the big picture of (A) blueprint (B) docker image hosting (C) scheduler will help guide us toward a suggestion.

**Comment by noahharrison64** [comment]
Hi,

Apologies for the slow reply on my behalf 
The blueprint I am using can be found [here](https://drive.google.com/file/d/1Bd1dIZp3-4RHdDD2uCZ5HTRkYD2yV4lm/view?usp=sharing) 
The docker image is hosted in a private google artifact registry 
I am using slurm as the scheduler.

Many thanks ,
Noah

**Comment by tpdownes** [comment]
I suggest the following, though I'm not in a position to test it without my own images in artifact registry to work with. This is an interesting problem customers often run into.

1. Add the [docker credential helper](https://cloud.google.com/artifact-registry/docs/docker/authentication#standalone-helper) and `docker pull` to the end of your script. This is a suggestion that you should review carefully and probably test on a live VM first:

```
VERSION=2.1.10
OS=linux  # or "darwin" for OSX, "windows" for Windows.
ARCH=amd64  # or "386" for 32-bit OSs

curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${VERSION}/docker-credential-gcr_${OS}_${ARCH}-${VERSION}.tar.gz" \
| tar xz docker-credential-gcr \
&& chmod +x docker-credential-gcr && sudo mv docker-credential-gcr /usr/bin/
docker-credential-gcr configure-docker --registries=us-central1-docker.pkg.dev
docker pull your-registry/your-image
```

Make sure to change the registry identified by the regional registry (us-central1 above) to what you need. Additionally, change the scopes setting on the packer module to "cloud-platform":

```yaml
- group: packer
  modules:
  - id: custom-image
    source: modules/packer/custom-image
    kind: packer
    settings:
      ...
      scopes:
      - https://www.googleapis.com/auth/cloud-platform
```

I will probably change the default scopes to cloud-platform as the current default causes more confusion than good.

**Comment by noahharrison64** [comment]
Hi Tom, that's brilliant thanks for your suggestion. I'll have a go at implementing and see where I get to. 

I also wanted to quickly check whether there was anything in my blueprint file missing that might allow me to SSH into the login node via command line? 

I assume this is an issue with Google's compute engine, but having setup the cluster I can access the login node via the in-browser SSH tool, where keys are auto-transferred, but trying to login via gcloud CLI on my local workstation leads to a connection time out. I've checked for an allow-ssh firewall rule, as well as adding my public SSH key to the project metadata. I've raised this issue with google cloud support but so far they've been unable to help.

**Comment by tpdownes** [comment]
The vpc module your blueprint uses establishes tunneling firewall rules using [Identity-Aware Proxy](https://cloud.google.com/iap/docs/using-tcp-forwarding#gcloud_2). If you use the `--tunnel-through-iap` flag, it will automatically select that approach instead of trying other alternatives first (i.e. it wastes less time).

```
gcloud compute ssh login-node-name --zone us-central1-c --tunnel-through-iap
```

Let me know if that works.

**Comment by noahharrison64** [comment]
I've spent so long trying to figure out what was going wrong, I can't believe it was this simple. Thanks so much for pointing that out! I'll report back next week on the docker image pre-install for the compute nodes.

**Comment by noahharrison64** [comment]
Hi Tom,

I had to make some modifications to get the code you suggested to work in a VM, am yet to try it in Packer but now it's running in the VM I'm hoping it should be straight forward. I had to generate a service account access token which I think is valid for 60 minutes, so will add it to the blueprint file and then run the create/deploy  HPC commands.

```
  #! /bin/sh					
VERSION=2.1.10
OS=linux  
ARCH=amd64 
curl -fsSL https://get.docker.com -o install-docker.sh
cat install-docker.sh
curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${VERSION}/docker-credential-gcr_${OS}_${ARCH}-${VERSION}.tar.gz" \
| tar xz docker-credential-gcr \
&& chmod +x docker-credential-gcr && sudo mv docker-credential-gcr /usr/bin/
docker-credential-gcr configure-docker --registries=us-central1-docker.pkg.dev
sudo chmod 666 /var/run/docker.sock
echo "acces token here" | docker login -u oauth2accesstoken     --password-stdin https://us-central1-docker.pkg.dev
gcloud auth configure-docker us-central1-docker.pkg.dev
docker pull us-central1-docker.pkg.dev/path_to_image
```

Will see if this works in Packer tomorrow. I also wanted to quickly ask if you could suggest how I may increase the time a compute node is idle for before shutting down the VM? I.e., I would like to wait for 20 mins of inactivity before the VM shuts down, at the moment I think it's a fair bit faster than that.

Thanks
Noah

**Comment by tpdownes** [comment]
I should have spelled this last bit out for you a bit more fully, sorry. You should be able to run

```
gcloud auth print-access-token
```

all by itself  inside any VM (including the one created by Packer). It will automatically use the service account attached to the VM. If you haven't specified a service account to the VM (your blueprint doesn't) it will use the "default Compute Engine service account" which should have permissions to pull from Artifact Registry.

**Comment by noahharrison64** [comment]
Hmm when I try running  either
```
echo gcloud auth print-access-token | docker login -u oauth2accesstoken     --password-stdin
echo gcloud auth print-access-token | docker login -u oauth2accesstoken     --password-stdin https://us-central1-docker.pkg.dev
```

I get the following errors respectively:
```
Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
Error response from daemon: Get "https://us-central1-docker.pkg.dev/v2/": unauthorized: failed authentication
```
As you suggested the VM is using the default compute engine service account.
Using the token from my workstation that is set/active on my non-service gcloud account appears to work no problem. 

And thanks for the details r..e SuspendTime

**Comment by noahharrison64** [comment]
I also have a couple of follow up questions r..e this setup:

1. If I want to make updates to my docker image, i.e. pull the most recent docker image that has had small changes on the top-most layers (such as a change to a git repo) would I need to destroy the HPC cluster and then re-deploy it so my compute instance templates contain the most up-to-date docker image? 
It seems like I could just add a 'docker pull' call in my sbatch submit.sh script, and since most of the image would be cached the pull on the compute node wouldn't take too long. However I get the impression updating the VM instance image would still save some time overall. 
2. I tried submitting some jobs via slurm this morning and they've been in the squeue with status 'pending' for nodelist(reason) 'BeginTime'. Checking via scontrol I see the AdminComment 'Region does not currently have sufficient capacity for the requested resources.'. I've encountered resource issues with GCP VMs before so I'm assuming this is the same issue. If I wanted to change the region in which my compute nodes are booting up would I have to re-modify the blueprint file and then re-deploy the cluster? 

Thanks!

**Comment by tpdownes** [comment]
## Issue 1: Access token

Do not run `echo gcloud...` as that literally prints the gcloud command to stdout. You want to run this so that the token is piped to the subsequent command:

```
gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
```

## Issue 2: GPUs

I didn't notice the Tesla T4s in your blueprint. I suggest a couple things:

1. CentOS 7 Slurm image will be EOL at end of the year. You might consider using the Rocky 8 image in your Packer build ([list of images from v5 slurm-gcp](https://github.com/SchedMD/slurm-gcp/blob/v5/docs/images.md#published-image-family)):

```yaml
      source_image_family: slurm-gcp-5-7-hpc-rocky-linux-8
```

2.  In addition to Docker, install the NVIDIA Container Toolkit and our Fast Socket plugin by adding following to your script (I'm assuming Rocky 8 by using `dnf`). I have a working blueprint for this using Debian 11, however, I'm adapting it for Rocky Linux 8 (i.e. this workflow has been tested on Debian 11 using apt package manager and should work for Rocky 8). See links below for upstream docs.

```
tee /etc/yum.repos.d/google-fast-socket.repo << EOM
[google-fast-socket]
name=Fast Socket Transport for NCCL
baseurl=https://packages.cloud.google.com/yum/repos/google-fast-socket
enabled=1
gpgcheck=0
repo_gpgcheck=0
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOM
yum install -y google-fast-socket

# note on line below the dollar sign is escaped for use in a GHPC YAML blueprint
# if you test this directly, removing the backslash after equals sign
distribution=\$(. /etc/os-release;echo $ID$VERSION_ID) \
    && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.repo | \
    tee /etc/yum.repos.d/nvidia-container-toolkit.repo
dnf clean expire-cache
dnf install -y nvidia-container-toolkit
```

3. SSH to the controller (`gcloud compute ssh HOSTNAME --zone ZONE --tunnel-through-iap`) and add the user you want to use Docker to the posix group named `docker`:

```
sudo gpasswd -a USER docker 
```

4. Submit jobs as that user while requesting a GPU in Slurm

```
srun -p compute --gpus=1 docker run --gpus all --rm nvcr.io/nvidia/tensorflow:23.07-tf2-py3 python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU')
```

### Links for above

- [Fast Socket](https://cloud.google.com/compute/docs/gpus/optimize-gpus#manual-fast-socket)
- [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#step-1-install-nvidia-container-toolkit)

**Comment by noahharrison64** [comment]
Hi,

Thanks for the detailed reply.
R.e. issue 2 - it appears that this image isn't supported by docker? So I haven't had success using this method, happy to try using Debian 11 but unclear how I need to modify your install scripts. 

I've tried using my own nvidia-toolkit install (detailed below) but get an error when running the GPU driver installation since there is no GPU attached to the packer VM. Would specifying a GPU overcome this issue?

```
        content: |
          #! /bin/sh
          #Set versions
          VERSION=2.1.10
          OS=linux
          ARCH=amd64
          
          #Install docker
          curl -fsSL https://get.docker.com -o install-docker.sh
          cat install-docker.sh
          sudo sh install-docker.sh

          #Install nvidia-toolkit
          . /etc/os-release
          distribution="${ID}${VERSION_ID}"
          curl https://raw.githubusercontent.com/GoogleCloudPlatform/compute-gpu-installation/main/linux/install_gpu_driver.py --output install_gpu_driver.py
          sudo python3 install_gpu_driver.py
          curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg       && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list |             sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' |             sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
          sudo apt-get update
          sudo nvidia-ctk runtime configure --runtime=docker
          sudo systemctl restart docker


          #Install docker-credential-gcr and authenticate docker
          curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${VERSION}/docker-credential-gcr_${OS}_${ARCH}-${VERSION}.tar.gz" \
            | tar xz docker-credential-gcr \
            && chmod +x docker-credential-gcr && sudo mv docker-credential-gcr /usr/bin/
          docker-credential-gcr configure-docker --registries=us-central1-docker.pkg.dev
          sudo chmod 666 /var/run/docker.sock
          gcloud auth print-access-token | docker login -u oauth2accesstoken     --password-stdin https://us-central1-docker.pkg.dev
          gcloud auth configure-docker us-central1-docker.pkg.dev

          #Pull docker image
          docker pull us-central1-docker.pkg.dev/path_to_image
```

Having been stuck on this issue for quite a while I'm now thinking of alternatives - is it possible for me to boot up a VM in GCP using a slurm-gcp image, install all the necessary parts separately (docker, nvidia-toolkit, my docker image) and then save this as a template that I can specify in the compute_node_group?

**Comment by tpdownes** [comment]
@noahharrison64 the last error message about scopes is addressed by an earlier suggestion I made that didn't make it's way into the blueprint. #1627 will make the setting you need the default value in future release of the Toolkit. Since I've made a few suggestions over course of thread, I've massaged your blueprint below. It makes a few changes:

1. Reverts to CentOS 7. I'm sorry that the Docker script doesn't support Rocky.
2. It will allow your compute nodes to be provisioned in any zone in us-central1 (this gives you a better chance of getting GPUs which are highly in demand)

If you get a message "there was a problem with the boot of the node" (or similar), review `/var/log/slurm/resume.log` on the controller. It may indicate that it could not provision a GPU node for you due to demand/capacity. 

We've captured the frustrations you've experienced to address in our roadmap so that we can simplify the Docker, GPU, Slurm end-to-end experience. At this point you should be able to login to the controller and run:

```
# $USER resolves to the the logged in user and adds them to the docker group
sudo gpasswd -a $USER docker
srun -p compute --gpus=1 docker run --gpus all --rm nvcr.io/nvidia/tensorflow:23.07-tf2-py3 python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU')"
```

If you run into something like "srun: error: Something is wrong with the boot of the nodes." I suggest you review `/var/log/slurm/resume.log` on the controller. It may inform you of capacity issues in the region. In that instance, you could pick a different region.

## Blueprint

I've commented out the homefs module and every instance it gets  to make it quicker to deploy and test the related functionality. You probably want to add it back in. I supply it exactly as I've tested it.

```yaml
---
blueprint_name: fep
vars:
  project_id: gcp-fep-experiment-001
  deployment_name: fep
  region: us-central1
  zone: us-central1-c
  new_image_family: fep-image
  disk_size: 128

deployment_groups:
- group: primary
  modules:
  - id: network1
    source: modules/network/vpc

  # - id: homefs
  #   source: modules/file-system/filestore
  #   use: [network1]
  #   settings:
  #     local_mount: /home

  - id: scripts_for_image
    source: modules/scripts/startup-script
    settings:
      runners:
      - type: shell
        destination: generate_hello.sh
        content: |
          #!/bin/bash

          set -e -o pipefail

          VERSION=2.1.10
          OS=linux
          ARCH=amd64

          # Install docker
          curl -fsSL https://get.docker.com -o install-docker.sh
          sh install-docker.sh
          systemctl enable docker
          systemctl start docker

          # Install nvidia-container-toolkit
          tee /etc/yum.repos.d/google-fast-socket.repo << EOM
          [google-fast-socket]
          name=Fast Socket Transport for NCCL
          baseurl=https://packages.cloud.google.com/yum/repos/google-fast-socket
          enabled=1
          gpgcheck=0
          repo_gpgcheck=0
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          EOM

          # note on line below the dollar sign is escaped for use in a GHPC YAML blueprint
          # if you test this directly, removing the backslash after equals sign
          distribution=\$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.repo | \
              tee /etc/yum.repos.d/nvidia-container-toolkit.repo
          yum install -y google-fast-socket nvidia-container-toolkit

          # Install docker credential-gcr and authenticate docker, pulling private image
          curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${VERSION}/docker-credential-gcr_${OS}_${ARCH}-${VERSION}.tar.gz" | tar xz docker-credential-gcr
          chmod +x docker-credential-gcr
          mv docker-credential-gcr /usr/bin/
          docker-credential-gcr configure-docker --registries=us-central1-docker.pkg.dev
          chmod 666 /var/run/docker.sock
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
          gcloud auth configure-docker us-central1-docker.pkg.dev
          # docker pull us-central1-docker.pkg.dev/path_to_private_image

- group: packer
  modules:
  - id: custom-image
    source: modules/packer/custom-image
    kind: packer
    use:
    - network1
    - scripts_for_image
    settings:
      source_image_project_id: [schedmd-slurm-public]
      source_image_family: slurm-gcp-5-7-hpc-centos-7
      image_family: $(vars.new_image_family)
      state_timeout: 15m
      scopes:
      - https://www.googleapis.com/auth/cloud-platform

- group: cluster
  modules:
  - id: compute_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 20
      machine_type: n1-standard-8
      guest_accelerator:
      - type: nvidia-tesla-t4
        count: 1
      disk_size_gb: $(vars.disk_size)
      instance_image:
        family: $(vars.new_image_family)
        project: $(vars.project_id)

  - id: compute_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    # - homefs
    - compute_node_group
    settings:
      partition_name: compute
      is_default: true
      exclusive: false
      enable_placement: false
      zones:
      - us-central1-a
      - us-central1-b
      - us-central1-c
      - us-central1-f

  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    use:
    - network1
    - compute_partition
    # - homefs
    settings:
      disable_controller_public_ips: false
      disk_size_gb: $(vars.disk_size)
      instance_image:
        family: $(vars.new_image_family)
        project: $(vars.project_id)
      cloud_parameters:
        resume_rate: 0
        resume_timeout: 600
        suspend_rate: 0
        suspend_timeout: 300
        no_comma_params: false

  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-login
    use:
    - network1
    - slurm_controller
    settings:
      machine_type: n2-standard-4
      disable_login_public_ips: false
      disk_size_gb: $(vars.disk_size)
      instance_image:
        family: $(vars.new_image_family)
        project: $(vars.project_id)
```

**Comment by noahharrison64** [comment]
Ah  this works perfectly, thanks so much I really appreciate the support.

I appear to have to run the following every time I log in to the login node. I've added this to a startup script that takes any arguments passed to the gcloud compute ssh --command and re-executes it in the new shell that is started after newgrp docker is run. i.e.:
```
#!/bin/bash

sudo gpasswd -a $USER docker
user_grp=$(id -g)
if [ "$user_grp" != 977 ]; then
  if [ "$SHLVL" -eq 1 ]; then
    newgrp docker
  fi
fi

eval $1
~                         
```

**Comment by rohitramu** [comment]
I would actually recommend using the [OS Login feature](https://cloud.google.com/compute/docs/oslogin/manage-oslogin-in-an-org#linux-groups) to manage group memberships.

These are the steps you'd need to take:
1. [Enable OS Login for the organization](https://cloud.google.com/compute/docs/oslogin/manage-oslogin-in-an-org#enable_the_organization_policy)
2. [Enable OS Login for your project](https://cloud.google.com/hpc-toolkit/docs/setup/configure-environment#enable-oslogin)
3. [Create the `docker` group](https://cloud.google.com/identity/docs/how-to/create-posix-groups#creating_a_posix_group_from_a_new_google_group)
4. [Add your user account to the group](https://support.google.com/cloudidentity/answer/9400087?&ref_topic=7558943)

The next time you SSH into the VM, your POSIX user account should already be part of the `docker` group.

This would be a cleaner approach, since you can manage group memberships using IAM instead of per-VM.

**Comment by noahharrison64** [comment]
Do you know of any solutions that circumvents google groups?

**Comment by cboneti** [comment]
No, I believe using OS Login to create POSIX groups will require using Google groups.

**Comment by noahharrison64** [comment]
Okay thanks for the info!
I'm reaching my quota limit of 4 Tesla GPUs in US-Central-1. If I wanted to increase the number of compute nodes I can have running simultaneously above 4, can I simply add more zones outside of US-Central-1 to my compute partition? i.e.
```
  - id: compute_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    # - homefs
    - compute_node_group
    settings:
      partition_name: compute
      is_default: true
      exclusive: false
      enable_placement: false
      zones:
      - us-central1-a
      - us-central1-b
      - us-central1-c
      - us-central1-f
      -  asia-east1-a
      -  asia-east1-b
      - etc
```

Would there be performance implications of doing this, especially if I'm running docking with the mounting option where I mount the login node's home directory to a /data directory in the docker container (i.e. requiring communication between the US-based login node and potentially non-US-based compute nodes)?
