### ISSUE TITLE
Partition a208 misconfigured in hpc-interprise-slurm.yaml

### ISSUE THREAD

**Issue by yaroslavvb** [GoogleCloudPlatform/hpc-toolkit#1688]
Partition a208 in [hpc-enterprise-slurm.yaml](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/examples/hpc-enterprise-slurm.yaml) doesn't appear to be properly configured for its machine type (`a2-ultragpu-8g`). The reason is that this machine has two sockets, and two-socket 8-GPU systems usually are split into two zones, 1 socket + 4 GPUs per zone.

When using asynchronous GPU memory transfers, some applications can bypass GPU and write to memory directly, as long as they are in the same zone. This is used by using `pin_memory=True` setting in PyTorch which is the standard.

However, that .yaml creates Slurm allocation without topology awareness. You end up 1 GPU jobs jobs being assigned CPUs/GPUs from different zones, this gives errors like below when using PyTorch on that config:

```srun: error: CPU binding outside of job step allocation, allocated CPUs are: 0x000000000001.```

**Comment by cboneti** [comment]
Hi Yaroslav, 

Thank you for pointing this out. This can be adjusted by changing the node group and partition definition to: 
```
 - id: a2_8_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 16
      machine_type: a2-ultragpu-8g
      bandwidth_tier: gvnic_enabled
      instance_image:
        family: $(vars.family)
        project: $(vars.project)
      disk_type: pd-ssd
      disk_size_gb: 100
      node_conf:
        Sockets: 2
        CoresPerSocket: 24
      service_account:
        email: $(compute_sa.service_account_email)
        scopes:
        - https://www.googleapis.com/auth/cloud-platform

  # use `-p a208` to submit jobs to this partition:
  # ex: `srun -p a208 --gpus-per-node=8 -N 1 nvidia-smi`
  - id: a2_8_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use: [a2_8_node_group, network1, homefs, projectsfs, scratchfs]
    settings:
      partition_name: a208
      # This makes this partition look for machines in any of the following zones
      # https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/develop/community/modules/compute/schedmd-slurm-gcp-v5-partition#compute-vm-zone-policies
      zones: $(vars.gpu_zones)
      partition_conf:
        DefMemPerGPU: 160000
        DefMemPerCPU: null
```

I will submit a PR to fix this in the example file shortly.
