### ISSUE TITLE
Example of startup script with cluster without vm-instance?

### ISSUE THREAD

**Issue by vsoch** [GoogleCloudPlatform/hpc-toolkit#2202]
Hi! Most of the examples with startup-script have an associated vm-instance, e.g.,

```
- id: startup
  source: ./modules/scripts/startup-script
  settings:
    runners:
      # Some modules such as filestore have runners as outputs for convenience:
      - $(homefs.install_nfs_client_runner)
      # These runners can still be created manually:
      # - type: shell
      #   destination: "modules/filestore/scripts/install_nfs_client.sh"
      #   source: "modules/filestore/scripts/install_nfs_client.sh"
      - type: ansible-local
        destination: "modules/filestore/scripts/mount.yaml"
        source: "modules/filestore/scripts/mount.yaml"
      - type: data
        source: /tmp/foo.tgz
        destination: /tmp/bar.tgz
      - type: shell
        destination: "decompress.sh"
        content: |
          #!/bin/sh
          echo $2
          tar zxvf /tmp/$1 -C /
        args: "bar.tgz 'Expanding file'"

- id: compute-cluster
  source: ./modules/compute/vm-instance
  use: [homefs, startup]
```
I'm looking to deploy a simple slurm cluster and I just want a startup script to run and install stuff on each node. Where is there an example for that? Thanks!

**Comment by cboneti** [comment]
Hi!

What the "use" clause does is that it ties any output of the used module to a matching input (same name) of the module using it.  In the example you provide above, the vm-instance module has an input named "startup_script" that gets assigned $(startup.startup_script).   It is effectively equivalent of writing: 

```
- id: compute-cluster
  source: ./modules/compute/vm-instance
  use: [network1, homefs]
  settings: 
    startup_script: $(startup.startup_script)
```
(notice I added a network to your instance, as it should probably be defined) 

There are various hooks for startup scripts in the slurm modules.  For example, the [hpc-slurm-gromacs.yaml](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/fcdc5e5e484f2a2cea86a7ff9f13a9bdea969ee5/community/examples/hpc-slurm-gromacs.yaml#L115), ties the spack installation (which is a set of startup scripts) to the login node. 

Slurm controllers have various variables that allow you to tie a script directly to them, for example, on a [V5 controller](https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/develop/community/modules/scheduler/schedmd-slurm-gcp-v5-controller#input_compute_startup_script), the following would be possible: 

```
  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    use:
    - network1
    - homefs
    - startup 
    settings:
```
The above would expand as follows: 
```
  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    use:
    - network1
    - homefs
#    - startup 
    settings:
      compute_startup_script: $(startup.compute_startup_script)
      controller_startup_script: $(startup.controller_startup_script)
```

By defining only one of "compute_startup_script" or "controller_startup_script" you can effectively define where you would like your startup scripts to run. From your question, it sounds like you would like it to run on the compute nodes. 

Finally, another alternative, perhaps better suited for a production cluster, is the [ml-slurm.yaml](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/examples/ml-slurm.yaml) example, where you would bake the installation in the slurm image itself, saving some time at boot. 

Please let me know if this answers your question.
