### ISSUE TITLE
Unable to use destroy cluster created using examples/hpc-cluster-small.yaml

### ISSUE THREAD

**Issue by sandwichmaker** [GoogleCloudPlatform/hpc-toolkit#376]
### Describe the bug
When destroying a cluster created using `examples/hpc-cluster-small.yaml`

```
terraform -chdir=<dir> destroy
```

everything works but the network is unable to be destroyed because it complains that the firewall is still using the network.

```
module.network1.module.vpc.module.vpc.google_compute_network.network: Destroying... [id=projects/climate-modeling-285614/global/networks/lopez-net]
module.network1.module.vpc.module.vpc.google_compute_network.network: Still destroying... [id=projects/climate-modeling-285614/global/networks/lopez-net, 10s elapsed]
╷
│ Error: Error waiting for Deleting Network: The network resource 'projects/climate-modeling-285614/global/networks/lopez-net' is already being used by 'projects/climate-modeling-285614/global/firewalls/lopez-net-iyvrmjzsszuzmmbd5kdofnu3-4'
```

### Steps to reproduce

1. Create a cluster 
2. Destroy the cluster

### Expected behavior
Everything in the cluster should be destroyed and the destroy command should return without an error.

### Actual behavior

As described above I get an error that the firewall is still using it. Using the console to delete the network manually works.

### Version (`ghpc --version`)
```
[main] hpc-toolkit: ./ghpc --version
ghpc version v1.0.0
```
### Blueprint

If applicable, attach or paste the blueprint YAML used to produce the bug.

```yaml
blueprint_name: hpc-cluster-small

vars:
  project_id: climate-modeling-285614
  deployment_name: lopez
  region: us-central1
  zone: us-central1-c

deployment_groups:
- group: primary
  modules:
  # Source is an embedded module, denoted by "modules/*" without ./, ../, /
  # as a prefix. To refer to a local or community module, prefix with ./, ../ or /
  # Example - ./modules/network/vpc
  - source: modules/network/vpc
    kind: terraform
    id: network1

  - source: modules/file-system/filestore
    kind: terraform
    id: homefs
    use: [network1]
    settings:
      local_mount: /home

  - source: modules/compute/vm-instance
    kind: terraform
    id: compute
    use:
    - network1
    - homefs
    settings:
      instance_count: 8
      name_prefix: lopez-compute
      machine_type: c2-standard-60
```

### Expanded Blueprint

If applicable, please attach or paste the expanded blueprint. The expanded blueprint can be obtained by running `ghpc expand your-blueprint.yaml`.

Disregard if the bug occurs when running `ghpc expand ...` as well.

```yaml
blueprint_name: hpc-cluster-small
validators:
- validator: test_project_exists
  inputs:
    project_id: ((var.project_id))
- validator: test_region_exists
  inputs:
    project_id: ((var.project_id))
    region: ((var.region))
- validator: test_zone_exists
  inputs:
    project_id: ((var.project_id))
    zone: ((var.zone))
- validator: test_zone_in_region
  inputs:
    project_id: ((var.project_id))
    region: ((var.region))
    zone: ((var.zone))
validation_level: 1
vars:
  deployment_name: lopez
  labels:
    ghpc_blueprint: hpc-cluster-small
    ghpc_deployment: lopez
  project_id: climate-modeling-285614
  region: us-central1
  zone: us-central1-c
deployment_groups:
- group: primary
  terraform_backend:
    type: ""
    configuration: {}
  modules:
  - source: modules/network/vpc
    kind: terraform
    id: network1
    modulename: ""
    use: []
    wrapsettingswith: {}
    settings:
      deployment_name: ((var.deployment_name))
      project_id: ((var.project_id))
      region: ((var.region))
  - source: modules/file-system/filestore
    kind: terraform
    id: homefs
    modulename: ""
    use:
    - network1
    wrapsettingswith: {}
    settings:
      deployment_name: ((var.deployment_name))
      labels:
        ghpc_role: file-system
      local_mount: /home
      network_name: ((module.network1.network_name))
      project_id: ((var.project_id))
      region: ((var.region))
      zone: ((var.zone))
  - source: modules/compute/vm-instance
    kind: terraform
    id: compute
    modulename: ""
    use:
    - network1
    - homefs
    wrapsettingswith:
      network_storage:
      - flatten(
      - )
    settings:
      deployment_name: ((var.deployment_name))
      instance_count: 8
      labels:
        ghpc_role: compute
      machine_type: c2-standard-60
      name_prefix: lopez-compute
      network_self_link: ((module.network1.network_self_link))
      network_storage:
      - ((module.homefs.network_storage))
      project_id: ((var.project_id))
      subnetwork_self_link: ((module.network1.subnetwork_self_link))
      zone: ((var.zone))
  kind: terraform
terraform_backend_defaults:
  type: ""
  configuration: {}
```

### Execution environment

- OS: macOS
- Shell: bash
- go version: go version go1.18.3 darwin/arm64
