### ISSUE TITLE
Spack broken on Slurm v5 due to hardcoded 300s custom script timeout

### ISSUE THREAD

**Issue by m4r1k** [GoogleCloudPlatform/hpc-toolkit#536]
### Describe the bug

When deploying a blueprint that includes long running builds, SlurmGCP v5 has an hardcoded 300 seconds timeout and it fails.
https://github.com/SchedMD/slurm-gcp/blob/v5.1.0/scripts/setup.py#L564

Find please at the end of this report the blueprint

Follows the resulting error log (taken from /slurm/scripts/setup.log)
```text
2022-09-09 21:35:17,466 DEBUG: run_custom_scripts: custom scripts to run: /slurm/custom_scripts/(login_6onjpjm6.d/ghpc_startup.sh)
2022-09-09 21:35:17,466 INFO: running script ghpc_startup.sh
2022-09-09 21:40:17,488 ERROR: TimeoutExpired:
    command=/slurm/custom_scripts/login_6onjpjm6.d/ghpc_startup.sh
    timeout=300
    stdout:
```

### Steps to reproduce

1. `ghpc create <yaml blueprint file>`
2. `terraform -chdir=internal-hpc/primary init`
3. `terraform -chdir=internal-hpc/primary validate`
4. `terraform -chdir=internal-hpc/primary apply`

### Expected behavior

Just as much in Slurm v4 I was able to build stuff that takes long time (like Gromacs and GCC), I should be able to achieve the same in Slurm v5.

### Actual behavior

I cannot have a fully working setup that includes packages that takes long to compile.

### Version (`ghpc --version`)
`ghpc version v1.4.1`

### Blueprint
```yaml
---
blueprint_name: hpc-cluster
vars:
  project_id: internal-hpc
  deployment_name: internal-hpc
  region: europe-west4
  zone: europe-west4-b

# Documentation for each of the modules used below can be found at
# https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/modules/README.md

deployment_groups:
- group: primary
  modules:
  - source: modules/network/vpc
    kind: terraform
    settings:
      mtu: 8896
    id: network1

  ## Filesystems
  - source: modules/file-system/filestore
    kind: terraform
    id: appsfs
    use: [network1]
    settings:
      local_mount: /sw
      filestore_tier: BASIC_HDD
      size_gb: 1024

  - source: modules/file-system/filestore
    kind: terraform
    id: homefs
    use: [network1]
    settings:
      local_mount: /home
      filestore_tier: BASIC_SSD
      size_gb: 3072

  ## Spack Install Scripts
  - source: community/modules/scripts/spack-install
    kind: terraform
    id: spack
    settings:
      install_dir: /sw/spack
      spack_url: https://github.com/spack/spack
      spack_ref: v0.18.1
      log_file: /var/log/spack.log
      configs:
      - type: single-config
        scope: defaults
        content: "config:build_stage:/sw/spack/spack-stage"
      - type: file
        scope: defaults
        content: |
          modules:
            default:
              tcl:
                hash_length: 0
                all:
                  conflict:
                    - '{name}'
                projections:
                  all: '{name}/{version}-{compiler.name}-{compiler.version}'
      compilers:
      - gcc@12.1.0 target=x86_64
      packages:
      - intel-mpi@2018.4.274%gcc@12.1.0 target=x86_64_v3
      - intel-oneapi-mpi@2021.6.0%gcc@12.1.0 target=x86_64_v3
      ## https://github.com/spack/spack/blob/v0.18.1/lib/spack/external/archspec/json/cpu/microarchitectures.json

  - source: modules/scripts/startup-script
    kind: terraform
    id: spack-startup
    settings:
      runners:
      - type: shell
        source: modules/startup-script/examples/install_ansible.sh
        destination: install_ansible.sh
      - $(spack.install_spack_deps_runner)
      - $(spack.install_spack_runner)

  - source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    kind: terraform
    id: c2d
    use:
    - network1
    - homefs
    - appsfs
    settings:
      partition_name: c2d
      node_count_dynamic_max: 10
      enable_placement: true
      machine_type: "c2d-highcpu-112"
      disk_type: "pd-standard"
      disable_smt: true
      bandwidth_tier: "gvnic_enabled"
      is_default: true

  - source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    kind: terraform
    id: c2
    use:
    - network1
    - homefs
    - appsfs
    settings:
      partition_name: c2
      node_count_dynamic_max: 20
      enable_placement: true
      machine_type: "c2-standard-60"
      disk_type: "pd-standard"
      disable_smt: true
      bandwidth_tier: "gvnic_enabled"

  - source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    kind: terraform
    id: slurm_controller
    use:
    - network1
    - homefs
    - appsfs
    - c2d
    - c2
    settings:
      disk_type: "pd-ssd"
      disk_size_gb: 50
      machine_type: "t2d-standard-2"
      disable_controller_public_ips: true

  - source: community/modules/scheduler/schedmd-slurm-gcp-v5-login
    kind: terraform
    id: slurm_login
    use:
    - network1
    - homefs
    - appsfs
    - slurm_controller
    - spack-startup
    settings:
      disk_type: "pd-ssd"
      disk_size_gb: 50
      machine_type: "t2d-standard-32"

  - source: modules/monitoring/dashboard
    kind: terraform
    id: hpc_dashboard
```
