### ISSUE TITLE
Ubuntu Slurm v5 deploys with CentOS

### ISSUE THREAD

**Issue by Tristan-Kosciuch** [GoogleCloudPlatform/hpc-toolkit#753]
### Describe the bug

This blueprint deploys with centos instead of ubuntu 20.04:
https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/v1.9.0/community/examples/slurm-gcp-v5-ubuntu2004.yaml

I'm trying to setup an HPC cluster with Slurm on Ubuntu and DDN Exascaler. Whenever I deploy my blueprint, a centos image is used instead of schedmd-v5-slurm-22-05-4-ubuntu-2004-lts. I verified that I cannot even deploy the example [ubuntu slurm](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/community/examples/slurm-gcp-v5-ubuntu2004.yaml) cluster in a brand new GCP project and with a newly built ghcp binary.

### Steps to reproduce

1. make the ghpc binary
```
git clone git@github.com:GoogleCloudPlatform/hpc-toolkit.git
cd hpc-toolkit
make
./ghpc --version
./ghpc --help
```
2. download [this](https://github.com/GoogleCloudPlatform/hpc-toolkit/blob/main/community/examples/slurm-gcp-v5-ubuntu2004.yaml) blueprint
```
curl https://raw.githubusercontent.com/GoogleCloudPlatform/hpc-toolkit/main/community/examples/slurm-gcp-v5-ubuntu2004.yaml > slurm-gcp-v5-ubuntu2004.yaml
```
3. deploy the blueprint
```
./ghpc create slurm-gcp-v5-ubuntu2004.yaml --vars project_id=<PROJECT_ID>
```

### Expected behavior

The resulting slurm cluster will use this image: `schedmd-v5-slurm-22-05-4-ubuntu-2004-lts`, and will function properly.

### Actual behavior

A centos image is used, I believe the default `schedmd-v5-slurm-22-05-2-hpc-centos-7` but I deleted the infra already. The slurm configuration is also stuck in a failed state.

### Execution environment

- OS: macOS
- Shell bash
- go version: go version go1.19.3 darwin/amd64

**Comment by heyealex** [comment]
Hello and thank you for reporting this. I believe the issue is related to a recent change in the node-group/partition interface and how images are interpreted. 

I need to reproduce to verify and find a solution, I'll report back once I know more.

**Comment by heyealex** [comment]
I deployed the ubuntu example and was able to reproduce what you saw. The variable names for defining an image between the login and controller vs the partitions has diverged, which lead to the discrepancy in the example. The partition VMs were created with the ubuntu images still, but not the login and controller VMs.

A PR has been opened to address this (#754), but in the meantime you can workaround this by setting the `source_image_family` and `source_image_project` directly in the `schedmd-slurm-gcp-v5-login` and `schedmd-slurm-gcp-v5-controller` modules in the `slurm-gcp-v5-ubuntu2004.yaml` example blueprint:

```yaml
  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    use:
    - network1
    - debug_partition
    - compute_partition
    - homefs
    settings:
      disable_controller_public_ips: false
      source_image_family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
      source_image_project: projects/schedmd-slurm-public/global/images/family

  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-login
    use:
    - network1
    - slurm_controller
    settings:
      machine_type: n2-standard-4
      disable_login_public_ips: false
      source_image_family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
      source_image_project: projects/schedmd-slurm-public/global/images/family
```

**Comment by Tristan-Kosciuch** [comment]
Thanks, I still think Slurm is not starting properly but the ubuntu image is used. 

### Describe the bug

Preexisting NFS mount is not attaching, there is a prometheus error, other mounts are failing. I am also deploying into a pre existing VPC and subnet and that works. The output of `sudo journalctl -o cat -u google-startup-scripts`
```
Starting startup scripts (version 20220622.00-0ubuntu2~20.04.0).
No startup scripts to run.
Starting Google Compute Engine Startup Scripts...
google-startup-scripts.service: Succeeded.
Finished Google Compute Engine Startup Scripts.
Starting startup scripts (version 20220622.00-0ubuntu2~20.04.0).
No startup scripts to run.
Starting Google Compute Engine Startup Scripts...
google-startup-scripts.service: Succeeded.
Finished Google Compute Engine Startup Scripts.
Starting startup scripts (version 20220622.00-0ubuntu2~20.04.0).
Found startup-script in metadata.
startup-script: ping -q -w1 -c1 metadata.google.internal
startup-script: Successfully contacted metadata server
startup-script: ping -q -w1 -c1 8.8.8.8
startup-script: Internet access detected
startup-script: curl: (22) The requested URL returned error: 404 Not Found
startup-script: slurmgcpv5-slurm-devel not found in project metadata, skipping script update
startup-script: running python cluster setup script
Starting Google Compute Engine Startup Scripts...
startup-script: INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
startup-script: ERROR:__main__:config file not found: /slurm/scripts/config.yaml
startup-script: WARNING:__main__:/slurm/scripts/config.yaml not found
startup-script: INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
startup-script: ERROR: Error while getting metadata from http://metadata.google.internal/computeMetadata/v1/project/attributes/slurmgcpv5-slurm-devel
startup-script: INFO: Setting up login
startup-script: INFO: installing custom scripts:
startup-script: INFO: Set up network storage
startup-script: INFO: Setting up mount (nfs) <NFS_IP>:nfsshare to /home
startup-script: INFO: Setting up mount (nfs) slurmgcpv5-controller:/usr/local/etc/slurm to /usr/local/etc/slurm
startup-script: INFO: Setting up mount (nfs) slurmgcpv5-controller:/etc/munge to /etc/munge
startup-script: INFO: Setting up mount (nfs) slurmgcpv5-controller:/opt/apps to /opt/apps
startup-script: DEBUG: <module>: disabling prometheus support
startup-script: Traceback (most recent call last):
startup-script:   File "/usr/local/lib/python3.8/dist-packages/more_executors/_impl/metrics/__init__.py", line 15, in <module>
startup-script:     from .prometheus import PrometheusMetrics
startup-script:   File "/usr/local/lib/python3.8/dist-packages/more_executors/_impl/metrics/prometheus.py", line 3, in <module>
startup-script:     import prometheus_client  # pylint: disable=import-error
startup-script: ModuleNotFoundError: No module named 'prometheus_client'
startup-script: INFO: Waiting for '/home' to be mounted...
startup-script: INFO: Waiting for '/usr/local/etc/slurm' to be mounted...
startup-script: INFO: Waiting for '/etc/munge' to be mounted...
startup-script: INFO: Waiting for '/opt/apps' to be mounted...
startup-script: ERROR: mount of path '/etc/munge' failed: <class 'subprocess.CalledProcessError'>: Command '['mount', '/etc/munge']' returned non-zero exit status 32.
startup-script: ERROR: mount of path '/usr/local/etc/slurm' failed: <class 'subprocess.CalledProcessError'>: Command '['mount', '/usr/local/etc/slurm']' returned non-zero exit sta>
startup-script: ERROR: mount of path '/opt/apps' failed: <class 'subprocess.CalledProcessError'>: Command '['mount', '/opt/apps']' returned non-zero exit status 32.
startup-script: ERROR: mount of path '/home' failed: <class 'subprocess.CalledProcessError'>: Command '['mount', '/home']' returned non-zero exit status 32.
```

### Blueprint 

`slurm-ubuntu-v5.yaml`
```
blueprint_name: slurm-gcp-v5-ubuntu2004

vars:
  project_id:  ## Set GCP Project ID Here ##
  deployment_name: slurm-gcp-v5
  region: us-central1
  zone: us-central1-c
  instance_image:
    family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
    project: projects/schedmd-slurm-public/global/images/family

deployment_groups:
- group: primary
  modules:
  # Source is an embedded resource, denoted by "resources/*" without ./, ../, /
  # as a prefix. To refer to a local resource, prefix with ./, ../ or /
  # Example - ./resources/network/vpc
  - id: network1
    source: modules/network/pre-existing-vpc
    settings:
      network_name: <VPC_NAME>
      subnetwork_name: <SUBNETWORK_NAME>

  - id: homefs
    source: modules/file-system/pre-existing-network-storage
    settings:
      server_ip: <NFS_IP>
      remote_mount: nfsshare
      local_mount: /home
      fs_type: nfs

  - id: debug_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 4
      machine_type: n2-standard-2

  - id: debug_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    - homefs
    - debug_node_group
    settings:
      partition_name: debug
      enable_placement: false
      is_default: true

  - id: compute_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 20

  - id: compute_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    - homefs
    - compute_node_group
    settings:
      partition_name: compute

  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    use:
    - network1
    - debug_partition
    - compute_partition
    - homefs
    settings:
      disable_controller_public_ips: false
      source_image_family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
      source_image_project: projects/schedmd-slurm-public/global/images/family

  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-login
    use:
    - network1
    - slurm_controller
    settings:
      machine_type: n2-standard-4
      disable_login_public_ips: false
      source_image_family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
      source_image_project: projects/schedmd-slurm-public/global/images/family
```

**Comment by heyealex** [comment]
Thank you for sharing the full blueprint, I believe I was able to replicate the issue.

Quick Answer: 
remote mount in `pre-existing-network-storage` requires a `/` before it, `/nfsshare`
```yaml
  - id: homefs
    source: modules/file-system/pre-existing-network-storage
    settings:
      remote_mount: /nfsshare
      local_mount: /home
      fs_type: nfs
```

Full Explanation: 
The logs for the login node showed that none of the paths could be mounted because the controller had not successfully started up, and therefore had not exported the required directories yet. homefs on both the controller and login failed to mount because the nfsshare point must be a path in `network_storage`. 

In general, if the login node is failing at mounting the default paths, as your logs show, checking the startup progress on the controller VM will likely indicate the problem more clearly. 

I hope this gets you unblocked. If not, or if you run into any other problems with your deployment, please follow up here or in a new GitHub issue.
