### ISSUE TITLE
DDN Exascaler not auto mounting to Slurm

### ISSUE THREAD

**Issue by Tristan-Kosciuch** [GoogleCloudPlatform/hpc-toolkit#756]
### Describe the bug

I am deploying a slurm cluster with the DDN exascaler filesystem but the mount keeps failing and retrying until it eventually stops in a failed state. 
### Steps to reproduce

1. 
```
./ghpc create blueprint.yaml --vars project_id=<PROJECT_ID>
terraform -chdir=slurm-lustre-v5/primary init
terraform -chdir=slurm-lustre-v5/primary validate
terraform -chdir=slurm-lustre-v5/primary apply
```

### Expected behavior

The lustre filesystem will be mounted at the expected mount directory.

### Actual behavior

Mount fails on both the login and controller Slurm nodes. When sshing into either login or controller node, this message appears: `*** Slurm setup failed! Please view log: /slurm/scripts/setup.log ***`

### Version (`ghpc --version`)
1.9.0
### Blueprint

As you can see from the commented out sections of the blueprint, I tried mounting lustre the way I expected it to work with `use` and also with the `mount-at-startup` workaround. Both failed for me. I also tried with 2 oss nodes and that failed to mount as well.

```yaml
blueprint_name: slurm-and-lustre-v5

vars:
  project_id:  ## Set GCP Project ID Here ##
  deployment_name: slurm-lustre-v5
  region: us-central1
  zone: us-central1-c
  instance_image:
    family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
    project: projects/schedmd-slurm-public/global/images/family

deployment_groups:
- group: primary
  modules:
  # Source is an embedded module, denoted by "modules/*" without /home/apps/dvmdostem_shared_lib//, /home/apps/dvmdostem_shared_lib/./, /
  # as a prefix. To refer to a local or community module, prefix with /home/apps/dvmdostem_shared_lib//, /home/apps/dvmdostem_shared_lib/./ or /
  # Example - /home/apps/dvmdostem_shared_lib//modules/network/pre-existing-vpc
  - id: network1
    source: modules/network/pre-existing-vpc
    settings:
      network_name: slurm-gcp-v5-net
      subnetwork_name: slurm-gcp-v5-primary-subnet

  - id: homefs
    source: modules/file-system/pre-existing-network-storage
    settings:
      server_ip: <NFS_IP>
      remote_mount: /nfsshare
      local_mount: /home
      fs_type: nfs

  - id: lustrefs
    source: community/modules/file-system/DDN-EXAScaler
    use: [network1]
    settings:
      local_mount: /mnt/lustre
      mgs:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mds:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mdt:
        disk_bus: SCSI
        disk_type: pd-ssd
        disk_size: 100
        disk_count: 1
        disk_raid: false
      oss:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      ost:
        disk_bus: SCSI
        disk_type: pd-standard
        disk_size: 500
        disk_count: 1
        disk_raid: false
        
  # - id: mount-at-startup
  #   source: modules/scripts/startup-script
  #   settings:
  #     runners:
  #     - $(lustrefs.install_ddn_lustre_client_runner)
  #     - $(lustrefs.mount_runner)

  - id: debug_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 4
      machine_type: n2-standard-2

  - id: debug_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    - homefs
    # - mount-at-startup
    - lustrefs
    - debug_node_group
    settings:
      partition_name: debug
      enable_placement: false
      is_default: true

  - id: compute_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 20

  - id: compute_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    - homefs
    # - mount-at-startup
    - lustrefs
    - compute_node_group
    settings:
      partition_name: compute

  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    use:
    - network1
    - homefs
    # - mount-at-startup
    - lustrefs
    - debug_partition
    - compute_partition
    settings:
      machine_type: n2-standard-2
      disk_type: pd-standard
      source_image_family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
      source_image_project: projects/schedmd-slurm-public/global/images/family

  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-login
    use:
    - network1
    - slurm_controller
    settings:
      machine_type: n2-standard-2
      disk_type: pd-standard
      disable_login_public_ips: false
      source_image_family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
      source_image_project: projects/schedmd-slurm-public/global/images/family

  - id: hpc_dashboard
    source: modules/monitoring/dashboard
    outputs: [instructions]
```

### Expanded Blueprint

If applicable, please attach or paste the expanded blueprint. The expanded blueprint can be obtained by running `ghpc expand your-blueprint.yaml`.

Disregard if the bug occurs when running `ghpc expand ...` as well.

```yaml
blueprint_name: slurm-and-lustre-v5
validators:
  - validator: test_project_exists
    inputs:
      project_id: ((var.project_id))
  - validator: test_apis_enabled
    inputs: {}
  - validator: test_region_exists
    inputs:
      project_id: ((var.project_id))
      region: ((var.region))
  - validator: test_zone_exists
    inputs:
      project_id: ((var.project_id))
      zone: ((var.zone))
  - validator: test_zone_in_region
    inputs:
      project_id: ((var.project_id))
      region: ((var.region))
      zone: ((var.zone))
validation_level: 1
vars:
  deployment_name: slurm-lustre-v5
  instance_image:
    family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
    project: projects/schedmd-slurm-public/global/images/family
  labels:
    ghpc_blueprint: slurm-and-lustre-v5
    ghpc_deployment: slurm-lustre-v5
  project_id: <PROJECT_ID>
  region: us-central1
  zone: us-central1-c
deployment_groups:
  - group: primary
    terraform_backend:
      type: ""
      configuration: {}
    modules:
      - source: modules/network/pre-existing-vpc
        kind: terraform
        id: network1
        modulename: ""
        use: []
        wrapsettingswith: {}
        settings:
          network_name: slurm-gcp-v5-net
          project_id: ((var.project_id))
          region: ((var.region))
          subnetwork_name: slurm-gcp-v5-primary-subnet
        required_apis:
          ((var.project_id)):
            - compute.googleapis.com
      - source: modules/file-system/pre-existing-network-storage
        kind: terraform
        id: homefs
        modulename: ""
        use: []
        wrapsettingswith: {}
        settings:
          fs_type: nfs
          local_mount: /home
          remote_mount: /nfsshare
          server_ip: <NFS_IP>
        required_apis:
          ((var.project_id)): []
      - source: community/modules/file-system/DDN-EXAScaler
        kind: terraform
        id: lustrefs
        modulename: ""
        use:
          - network1
        wrapsettingswith: {}
        settings:
          labels:
            ghpc_role: file-system
          local_mount: /mnt/lustre
          mds:
            nic_type: GVNIC
            node_count: 1
            node_cpu: Intel Cascade Lake
            node_type: n2-standard-2
            public_ip: true
          mdt:
            disk_bus: SCSI
            disk_count: 1
            disk_raid: false
            disk_size: 100
            disk_type: pd-ssd
          mgs:
            nic_type: GVNIC
            node_count: 1
            node_cpu: Intel Cascade Lake
            node_type: n2-standard-2
            public_ip: true
          network_self_link: ((module.network1.network_self_link))
          oss:
            nic_type: GVNIC
            node_count: 1
            node_cpu: Intel Cascade Lake
            node_type: n2-standard-2
            public_ip: true
          ost:
            disk_bus: SCSI
            disk_count: 1
            disk_raid: false
            disk_size: 500
            disk_type: pd-standard
          project_id: ((var.project_id))
          subnetwork_address: ((module.network1.subnetwork_address))
          subnetwork_self_link: ((module.network1.subnetwork_self_link))
          zone: ((var.zone))
        required_apis:
          ((var.project_id)):
            - compute.googleapis.com
            - deploymentmanager.googleapis.com
            - iam.googleapis.com
            - runtimeconfig.googleapis.com
      - source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
        kind: terraform
        id: debug_node_group
        modulename: ""
        use: []
        wrapsettingswith: {}
        settings:
          instance_image: ((var.instance_image))
          labels:
            ghpc_role: compute
          machine_type: n2-standard-2
          node_count_dynamic_max: 4
          project_id: ((var.project_id))
        required_apis:
          ((var.project_id)): []
      - source: community/modules/compute/schedmd-slurm-gcp-v5-partition
        kind: terraform
        id: debug_partition
        modulename: ""
        use:
          - network1
          - homefs
          - lustrefs
          - debug_node_group
        wrapsettingswith:
          network_storage:
            - flatten(
            - )
          node_groups:
            - flatten(
            - )
        settings:
          deployment_name: ((var.deployment_name))
          enable_placement: false
          is_default: true
          labels:
            ghpc_role: compute
          network_storage:
            - ((module.homefs.network_storage))
            - ((module.lustrefs.network_storage))
          node_groups:
            - ((module.debug_node_group.node_groups))
          partition_name: debug
          project_id: ((var.project_id))
          region: ((var.region))
          subnetwork_self_link: ((module.network1.subnetwork_self_link))
          zone: ((var.zone))
        required_apis:
          ((var.project_id)):
            - compute.googleapis.com
      - source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
        kind: terraform
        id: compute_node_group
        modulename: ""
        use: []
        wrapsettingswith: {}
        settings:
          instance_image: ((var.instance_image))
          labels:
            ghpc_role: compute
          node_count_dynamic_max: 20
          project_id: ((var.project_id))
        required_apis:
          ((var.project_id)): []
      - source: community/modules/compute/schedmd-slurm-gcp-v5-partition
        kind: terraform
        id: compute_partition
        modulename: ""
        use:
          - network1
          - homefs
          - lustrefs
          - compute_node_group
        wrapsettingswith:
          network_storage:
            - flatten(
            - )
          node_groups:
            - flatten(
            - )
        settings:
          deployment_name: ((var.deployment_name))
          labels:
            ghpc_role: compute
          network_storage:
            - ((module.homefs.network_storage))
            - ((module.lustrefs.network_storage))
          node_groups:
            - ((module.compute_node_group.node_groups))
          partition_name: compute
          project_id: ((var.project_id))
          region: ((var.region))
          subnetwork_self_link: ((module.network1.subnetwork_self_link))
          zone: ((var.zone))
        required_apis:
          ((var.project_id)):
            - compute.googleapis.com
      - source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
        kind: terraform
        id: slurm_controller
        modulename: ""
        use:
          - network1
          - homefs
          - lustrefs
          - debug_partition
          - compute_partition
        wrapsettingswith:
          network_storage:
            - flatten(
            - )
          partition:
            - flatten(
            - )
        settings:
          deployment_name: ((var.deployment_name))
          disk_type: pd-standard
          labels:
            ghpc_role: scheduler
          machine_type: n2-standard-2
          network_self_link: ((module.network1.network_self_link))
          network_storage:
            - ((module.homefs.network_storage))
            - ((module.lustrefs.network_storage))
          partition:
            - ((module.debug_partition.partition))
            - ((module.compute_partition.partition))
          project_id: ((var.project_id))
          region: ((var.region))
          source_image_family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
          source_image_project: projects/schedmd-slurm-public/global/images/family
          subnetwork_self_link: ((module.network1.subnetwork_self_link))
          zone: ((var.zone))
        required_apis:
          ((var.project_id)):
            - compute.googleapis.com
            - iam.googleapis.com
            - pubsub.googleapis.com
            - secretmanager.googleapis.com
      - source: community/modules/scheduler/schedmd-slurm-gcp-v5-login
        kind: terraform
        id: slurm_login
        modulename: ""
        use:
          - network1
          - slurm_controller
        wrapsettingswith: {}
        settings:
          controller_instance_id: ((module.slurm_controller.controller_instance_id))
          deployment_name: ((var.deployment_name))
          disable_login_public_ips: false
          disk_type: pd-standard
          labels:
            ghpc_role: scheduler
          machine_type: n2-standard-2
          network_self_link: ((module.network1.network_self_link))
          project_id: ((var.project_id))
          region: ((var.region))
          source_image_family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
          source_image_project: projects/schedmd-slurm-public/global/images/family
          subnetwork_self_link: ((module.network1.subnetwork_self_link))
          zone: ((var.zone))
        required_apis:
          ((var.project_id)):
            - compute.googleapis.com
      - source: modules/monitoring/dashboard
        kind: terraform
        id: hpc_dashboard
        modulename: ""
        use: []
        wrapsettingswith: {}
        outputs:
          - instructions
        settings:
          deployment_name: ((var.deployment_name))
          project_id: ((var.project_id))
        required_apis:
          ((var.project_id)):
            - stackdriver.googleapis.com
    kind: terraform
terraform_backend_defaults:
  type: ""
  configuration: {}
```

### Output and logs

output of `sudo journalctl -o cat -u google-startup-scripts` from the controller node
```text
Starting startup scripts (version 20220622.00-0ubuntu2~20.04.0).
No startup scripts to run.
Starting Google Compute Engine Startup Scripts...
google-startup-scripts.service: Succeeded.
Finished Google Compute Engine Startup Scripts.
Starting startup scripts (version 20220622.00-0ubuntu2~20.04.0).
No startup scripts to run.
Starting Google Compute Engine Startup Scripts...
google-startup-scripts.service: Succeeded.
Finished Google Compute Engine Startup Scripts.
Starting startup scripts (version 20220622.00-0ubuntu2~20.04.0).
Found startup-script in metadata.
startup-script: ping -q -w1 -c1 metadata.google.internal
startup-script: Successfully contacted metadata server
startup-script: ping -q -w1 -c1 8.8.8.8
startup-script: Internet access detected
startup-script: curl: (22) The requested URL returned error: 404 Not Found
startup-script: slurmlustr-slurm-devel not found in project metadata, skipping script update
startup-script: running python cluster setup script
Starting Google Compute Engine Startup Scripts...
startup-script: INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
startup-script: ERROR:__main__:config file not found: /slurm/scripts/config.yaml
startup-script: WARNING:__main__:/slurm/scripts/config.yaml not found
startup-script: INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
startup-script: ERROR: Error while getting metadata from http://metadata.google.internal/computeMetadata/v1/project/attributes/slurmlustr-slurm-devel
startup-script: INFO: Setting up controller
startup-script: INFO: installing custom scripts:
startup-script: DEBUG: compute_service: Using version=v1 of Google Compute Engine API
startup-script: INFO: Munge key already exists. Skipping key generation.
startup-script: INFO: Set up network storage
startup-script: INFO: Setting up mount (nfs) 10.126.75.90:/nfsshare to /home
startup-script: INFO: Setting up mount (lustre) 10.0.0.59@tcp:/exacloud to /mnt/lustre
startup-script: DEBUG: <module>: disabling prometheus support
startup-script: Traceback (most recent call last):
startup-script:   File "/usr/local/lib/python3.8/dist-packages/more_executors/_impl/metrics/__init__.py", line 15, in <module>
startup-script:     from .prometheus import PrometheusMetrics
startup-script:   File "/usr/local/lib/python3.8/dist-packages/more_executors/_impl/metrics/prometheus.py", line 3, in <module>
startup-script:     import prometheus_client  # pylint: disable=import-error
startup-script: ModuleNotFoundError: No module named 'prometheus_client'
startup-script: INFO: Waiting for '/home' to be mounted...
startup-script: INFO: Waiting for '/mnt/lustre' to be mounted...
startup-script: ERROR: mount of path '/mnt/lustre' failed: <class 'subprocess.CalledProcessError'>: Command '['mount', '/mnt/lustre']' returned non-zero exit status 19.
startup-script: INFO: Waiting for '/mnt/lustre' to be mounted...
startup-script: ERROR: mount of path '/mnt/lustre' failed: <class 'subprocess.CalledProcessError'>: Command '['mount', '/mnt/lustre']' returned non-zero exit status 19.
startup-script: INFO: Mount point '/home' was mounted.
startup-script: INFO: Waiting for '/mnt/lustre' to be mounted...
startup-script: ERROR: mount of path '/mnt/lustre' failed: <class 'subprocess.CalledProcessError'>: Command '['mount', '/mnt/lustre']' returned non-zero exit status 19.
startup-script: INFO: Waiting for '/mnt/lustre' to be mounted...

# The failed mounting of /mnt/lustre message repeats 

startup-script: ERROR: CalledProcessError:
startup-script:     command=['mount', '/mnt/lustre']
startup-script:     returncode=19
startup-script:     stdout:
startup-script:
startup-script:     stderr:
startup-script: mount.lustre: mount 10.0.0.59@tcp:/exacloud at /mnt/lustre failed: No such device
startup-script: Are the lustre modules loaded?
startup-script: Check /etc/modprobe.conf and /proc/filesystems
startup-script:
startup-script: ERROR: Aborting setup...
startup-script exit status 0
Finished running startup scripts.
google-startup-scripts.service: Succeeded.
Finished Google Compute Engine Startup Scripts.
```

### Execution environment

- OS: macOS
- Shell: bash
- go version: go1.19.3 darwin/amd64

**Comment by heyealex** [comment]
Thank you for providing this information. I will attempt to replicate and get back to you with any findings.

Given the error message, it's possible that the lustre server failed to startup correctly, you may want to inspect the startup logs from the VMs hosting Lustre to check if that's the case.

**Comment by Tristan-Kosciuch** [comment]
The [compute engine issue](https://status.cloud.google.com/incidents/UHoBgMgvvQKa18JQjdbs) has slowed my work a bit today, but you'd like the output of `sudo journalctl -o cat -u google-startup-scripts` from the various DDN nodes, right?

**Comment by heyealex** [comment]
I was able to replicate your failure, so I won't need the logs from the lustre VMs, as I can check my own. 

I've run a few tests, and it appears that the issue is with the ubuntu slurm image. I'm working to confirm that and hopefully find a solution. I'll keep this thread updated as I learn more.

**Comment by Tristan-Kosciuch** [comment]
Thanks! I got in to the slurm infra if you do need any logs.

**Comment by cboneti** [comment]
Hi Tristan, 
I am taking over from Alex here.  He was able to pinpoint the exact problem: the version of the driver installed in the Ubuntu image is creating this problem. I am working on a temporary workaround for you and should come back here shortly.

**Comment by cboneti** [comment]
Hi Tristan, 

Our native installation seems to work, We contacted SchedMD and they plan on releasing new images sometime this week.
 
In the meantime, the following workaround should allow you to get your environment working.   This builds a new image with the right drivers (based on [this example](https://github.com/GoogleCloudPlatform/hpc-toolkit/tree/develop/examples#image-builderyaml-)). 

I added two new deployment groups and made a few very minor modifications to your blueprint, as shown below. Please note that the changes in the nfs ip are simply to make it easy for me to overwrite that value from the command line.

```yaml
blueprint_name: slurm-and-lustre-v5

vars:
  project_id:  ## Set GCP Project ID Here ##
  deployment_name: slurm-lustre-v5
  region: us-central1
  zone: us-central1-c
  server_ip:
  startup_timeouts: 300
  network_name: slurm-gcp-v5-net
  subnetwork_name: slurm-gcp-v5-primary-subnet
  new_image_family: new-schedmd-v5-slurm-22-05-4-ubuntu-2004

deployment_groups:
- group: tmplustre-and-scripts
  modules:
  - id: network0
    source: modules/network/pre-existing-vpc
  - id: tmplustrefs
    source: community/modules/file-system/DDN-EXAScaler
    use: [network0]
    settings:
      local_mount: /mnt/lustre
      mgs:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mds:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mdt:
        disk_bus: SCSI
        disk_type: pd-ssd
        disk_size: 100
        disk_count: 1
        disk_raid: false
      oss:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      ost:
        disk_bus: SCSI
        disk_type: pd-standard
        disk_size: 500
        disk_count: 1
        disk_raid: false

  - id: mount-at-startup
    source: modules/scripts/startup-script
    settings:
      runners:
      - $(tmplustrefs.install_ddn_lustre_client_runner)
      - type: shell
        destination: "clean_up.sh"
        content: |
          #!/bin/bash
          esc-client unmount -m "/mnt/exacloud"
          rm /etc/esc-client.conf
    outputs: [startup_script]

- group: new-image
  modules:
  - id: custom-image
    source: modules/packer/custom-image
    kind: packer
    settings:
      omit_external_ip: false
      disk_size: 32
      source_image_project_id: [schedmd-slurm-public]
      source_image_family: schedmd-v5-slurm-22-05-4-ubuntu-2004-lts
      image_family: $(vars.new_image_family)

- group: primary
  modules:
  # Source is an embedded module, denoted by "modules/*" without /home/apps/dvmdostem_shared_lib//, /home/apps/dvmdostem_shared_lib/./, /
  # as a prefix. To refer to a local or community module, prefix with /home/apps/dvmdostem_shared_lib//, /home/apps/dvmdostem_shared_lib/./ or /
  # Example - /home/apps/dvmdostem_shared_lib//modules/network/pre-existing-vpc
  - id: network1
    source: modules/network/pre-existing-vpc

  - id: homefs
    source: modules/file-system/pre-existing-network-storage
    settings:
      server_ip: $(vars.server_ip)
      remote_mount: /nfsshare
      local_mount: /home
      fs_type: nfs

  - id: lustrefs
    source: community/modules/file-system/DDN-EXAScaler
    use: [network1]
    settings:
      local_mount: /mnt/lustre
      mgs:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mds:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mdt:
        disk_bus: SCSI
        disk_type: pd-ssd
        disk_size: 100
        disk_count: 1
        disk_raid: false
      oss:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      ost:
        disk_bus: SCSI
        disk_type: pd-standard
        disk_size: 500
        disk_count: 1
        disk_raid: false

  - id: debug_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 4
      machine_type: n2-standard-2
      instance_image:
        family: $(vars.new_image_family)
        project: $(vars.project_id)

  - id: debug_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    - homefs
    - lustrefs
    - debug_node_group
    settings:
      partition_name: debug
      enable_placement: false
      is_default: true

  - id: compute_node_group
    source: community/modules/compute/schedmd-slurm-gcp-v5-node-group
    settings:
      node_count_dynamic_max: 20
      instance_image:
        family: $(vars.new_image_family)
        project: $(vars.project_id)

  - id: compute_partition
    source: community/modules/compute/schedmd-slurm-gcp-v5-partition
    use:
    - network1
    - homefs
    - lustrefs
    - compute_node_group
    settings:
      partition_name: compute

  - id: slurm_controller
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-controller
    use:
    - network1
    - homefs
    - lustrefs
    - debug_partition
    - compute_partition
    settings:
      machine_type: n2-standard-2
      disk_type: pd-standard
      source_image_family: $(vars.new_image_family)
      source_image_project: $(vars.project_id)
      login_startup_scripts_timeout: $(vars.startup_timeouts)
      controller_startup_scripts_timeout: $(vars.startup_timeouts)
      compute_startup_scripts_timeout: $(vars.startup_timeouts)

  - id: slurm_login
    source: community/modules/scheduler/schedmd-slurm-gcp-v5-login
    use:
    - network1
    - slurm_controller
    settings:
      machine_type: n2-standard-2
      disk_type: pd-standard
      disable_login_public_ips: false
      source_image_family: $(vars.new_image_family)
      source_image_project: $(vars.project_id)

  - id: hpc_dashboard
    source: modules/monitoring/dashboard
    outputs: [instructions]

```

As you can see, we split the yaml into three groups. The first group creates a temporary lustre just to pull the drivers from, it will be destroyed after the image is created. You don’t have to deploy this again unless you want to build a new image.  


```shell
 ./ghpc create issue-756-b.yaml -w --vars project_id=<project_id>,server_ip=<server_ip>,network_name=<network name>,subnetwork_name=<subnetwork name>
terraform -chdir=slurm-lustre-v5/tmplustre-and-scripts init 
terraform -chdir=slurm-lustre-v5/tmplustre-and-scripts validate
terraform -chdir=slurm-lustre-v5/tmplustre-and-scripts apply
terraform -chdir=slurm-lustre-v5/tmplustre-and-scripts output  -raw startup_script_mount-at-startup > slurm-lustre-v5/new-image/custom-image/startup_script.sh
```

The second group is a packer group that creates a new image with the updated drivers. This should take around 10-15 minutes.

Notice that once your new image is created, you no longer need the temporary lustre installation and so we destroy it as the last command here.

```shell
cd slurm-lustre-v5/new-image/custom-image/
packer init . 
packer validate -var startup_script_file=startup_script.sh .
packer build -var startup_script_file=startup_script.sh .
cd -
terraform -chdir=slurm-lustre-v5/tmplustre-and-scripts destroy
```

Now that you have the new images, you can create your cluster as you were doing before (but using the new image), the last group is essentially your original blueprint, using your updated image and can be deployed independently once you have your image:

```shell 
terraform -chdir=slurm-lustre-v5/primary init
terraform -chdir=slurm-lustre-v5/primary validate
terraform -chdir=slurm-lustre-v5/primary apply
```

Please let me know if you get this working on your environment.
