### ISSUE TITLE
Failed to download DDN exascaler module

### ISSUE THREAD

**Issue by Tristan-Kosciuch** [GoogleCloudPlatform/hpc-toolkit#860]
### Describe the bug

The DDN exascaler module cannot be downloaded from github. 

terraform output:
```
│ Error: Failed to download module
│ 
│ Could not download module "ddn_exascaler" (modules/DDN-EXAScaler/main.tf:38) source code from
│ "git::https://github.com/DDNStorage/exascaler-cloud-terraform.git?ref=78deadb": error downloading
│ 'https://github.com/DDNStorage/exascaler-cloud-terraform.git?ref=78deadb': /usr/bin/git exited with 128: Cloning into
│ '.terraform/modules/tmplustrefs.ddn_exascaler'...
│ remote: Repository not found.
│ fatal: repository 'https://github.com/DDNStorage/exascaler-cloud-terraform.git/' not found
```

### Steps to reproduce

1. example blueprint:

```
blueprint_name: create-image

vars:
  project_id:  ## GCP Project ID ##
  ssh_username: ## Local username ##
  deployment_name: create-image
  region: us-central1
  zone: us-central1-c
  startup_timeouts: 300
  network_name: slurm-gcp-v5-net
  subnetwork_name: slurm-gcp-v5-primary-subnet

deployment_groups:
- group: tmplustre-and-scripts
  modules:
  - id: network0
    source: modules/network/pre-existing-vpc
  - id: tmplustrefs
    source: community/modules/file-system/DDN-EXAScaler
    use: [network0]
    settings:
      local_mount: /mnt/exacloud
      mgs:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mds:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      mdt:
        disk_bus: SCSI
        disk_type: pd-ssd
        disk_size: 100
        disk_count: 1
        disk_raid: false
      oss:
        node_type: n2-standard-2
        node_cpu: Intel Cascade Lake
        nic_type: GVNIC
        public_ip: true
        node_count: 1
      ost:
        disk_bus: SCSI
        disk_type: pd-standard
        disk_size: 500
        disk_count: 1
        disk_raid: false
```

2. deploy:
```
ghpc create blueprints/create-dvmdostem-image.yaml --vars project_id=$PROJECTID --vars ssh_username=$USER
terraform -chdir=create-image/tmplustre-and-scripts init
terraform -chdir=create-image/tmplustre-and-scripts validate
terraform -chdir=create-image/tmplustre-and-scripts apply
```

### Expected behavior

DDN Exascaler lustre filesystem will be created

### Actual behavior

The module cannot be found

### Version (`ghpc --version`)

```
ghpc version v1.9.0
Built from 'main' branch.
Commit info: v1.9.0-0-g0f0f70ea
```

### Expanded Blueprint

If applicable, please attach or paste the expanded blueprint. The expanded blueprint can be obtained by running `ghpc expand your-blueprint.yaml`.

Disregard if the bug occurs when running `ghpc expand ...` as well.

```yaml

```

### Output and logs

```text
│ Error: Failed to download module
│ 
│ Could not download module "ddn_exascaler" (modules/DDN-EXAScaler/main.tf:38) source code from
│ "git::https://github.com/DDNStorage/exascaler-cloud-terraform.git?ref=78deadb": error downloading
│ 'https://github.com/DDNStorage/exascaler-cloud-terraform.git?ref=78deadb': /usr/bin/git exited with 128: Cloning into
│ '.terraform/modules/tmplustrefs.ddn_exascaler'...
│ remote: Repository not found.
│ fatal: repository 'https://github.com/DDNStorage/exascaler-cloud-terraform.git/' not found
│ 
╵

co-tkosciuch:GCP-Slurm coadmin$ terraform -chdir=create-image/tmplustre-and-scripts validate
╷
│ Error: Module not installed
│ 
│   on modules/DDN-EXAScaler/main.tf line 38:
│   38: module "ddn_exascaler" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
```

### Execution environment

- OS: macOS
- Shell: bash
- go version: go version go1.19.3 darwin/amd64
